version: '3.7'
services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - "$MONGO_PORT:27017"
    volumes:
      - ./var/mongo:/data/db
    command: mongod --replSet $MONGO_REPLICA_SET
    environment:
      MONGO_REPLICA_SET: $MONGO_REPLICA_SET
  mongo-setup:
    image: mongo:4
    volumes:
      - ./dev/mongo/setup-mongo.sh:/setup-mongo.sh
    command: /setup-mongo.sh
    depends_on:
      - mongo
    environment:
      MONGO_PORT: $MONGO_PORT
      MONGO_REPLICA_SET: $MONGO_REPLICA_SET
  saml-idp:
    image: kristophjunge/test-saml-idp:1.15
    ports:
      - "$SAML_IDP_PORT:8080"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: $SAML_ISSUER
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: $SAML_SP_ACS
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: $SAML_SP_LOGOUT_URL
    volumes:
      - "./dev/saml/saml_authsources.php:/var/www/simplesamlphp/config/authsources.php"
