version: '3.7'
services:
  mongo:
    image: mongo:4
    restart: always
    ports:
      - "$MONGO_PORT:27017"
    volumes:
      - ./var/mongo:/data/db
  saml-idp:
    image: kristophjunge/test-saml-idp:1.15
    ports:
      - "$SAML_IDP_PORT:8080"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: $SAML_ISSUER
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: $SAML_SP_ACS
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: $SAML_SP_LOGOUT_URL
    volumes:
      - "./misc/dev/saml_authsources.php:/var/www/simplesamlphp/config/authsources.php"
