version: '3.7'
services:
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - ./var/mongo:/data/db
    command: mongod --replSet rs0
  mongo-setup:
    image: mongo:4
    volumes:
      - ./dev/mongo/setup-mongo.sh:/setup-mongo.sh
    command: /setup-mongo.sh
    depends_on:
      - mongo
    environment:
      MONGO_PORT: 27017
      MONGO_REPLICA_SET: rs0
  saml-idp:
    image: kristophjunge/test-saml-idp:1.15
    ports:
      - "8080:8080"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: dev
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: http://localhost:3000/api/sign/in/callback
    volumes:
      - "./dev/saml/saml_authsources.php:/var/www/simplesamlphp/config/authsources.php"
