name: feature

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install
      run: yarn install
    - name: Test
      run: |
        yarn lint
        yarn test
        yarn w/ui build
