name: test released packages

on:
  workflow_run:
    workflows:
      - master
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Create a project
      run: |
        npx @sheeted/cli project hello-world
      working-directory: node
    - name: Install and run
      run: |
        docker-compose up -d
        npm install
      working-directory: node/hello-world
    - name: Test
      run: |
        node build/app.js
      working-directory: node/hello-world
