name: test released packages

on:
  workflow_run:
    workflows:
      - master
    types:
      - completed

jobs:
  test_after_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Create a project
      run: |
        npm install -g @sheeted/cli
        sheeted project hello-world
    - name: Install
      run: |
        npm install
        npm run build
      working-directory: hello-world
    - name: Test
      run: |
        node build/app.js
      working-directory: hello-world
